---
title: "p8105_hw1_lc3391"
date: "09/17/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

#Problem 1

##Creating a data frame
```{r problem1_parta}
la_df= tibble(
  norm_samp = rnorm(8),
  norm_samp_pos = norm_samp > 0,
  vec_char = c("a","b","c","d","e","f","g","h"),
  vec_factor = factor(c("low","med","high","low","low","med","high","high"))

)

mean(pull(la_df, norm_samp))
mean(pull(la_df, norm_samp_pos))
mean(pull(la_df, vec_char))
mean(pull(la_df, vec_factor))

```

The mean of the numeric vector, norm_samp, is `r mean(pull(la_df, norm_samp))`.
The mean of the logical vector, norm_samp_pos is `r mean(pull(la_df, norm_samp_pos))`.
And NO mean could be taken for the character vector and factor vector.

##converting variables from one type to another
```{r problem1_partb, warning = FALSE}

#covert the logical vector to numeric and multiply the random samnple by the result
as.numeric(pull(la_df, norm_samp_pos))*pull(la_df, norm_samp)

#covert the logical vector to factor and multiply the random samnple by the result
as.factor(pull(la_df, norm_samp_pos))*pull(la_df, norm_samp)

#convert the logical vector to a factor and then convert the result to numeric, and multiply the random sample by the result
as.numeric(as.factor(pull(la_df, norm_samp_pos)))*pull(la_df, norm_samp)
```


#Problem 2
```{r problem2_part1}
p2_df= tibble(
  x = rnorm(500),
  y = rnorm(500),
  vec_log = x + y > 1
)
```

